# Generated by Django 3.2.16 on 2022-11-18 11:44

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('Department', models.CharField(blank=True, choices=[('IT', 'IT'), ('Design', 'Design'), ('Estimation', 'Estimation')], max_length=10, null=True)),
                ('Designation', models.CharField(blank=True, choices=[('Engineer', 'Engineer'), ('Sr_Engineer', 'Sr_Engineer'), ('Manager', 'Manager')], max_length=11, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('image', models.ImageField(default='photos/tandaslogodashboard.png', upload_to='photos/')),
                ('Team_Type', models.CharField(blank=True, choices=[('Frames', 'Frames'), ('Doors', 'Doors')], max_length=10, null=True)),
                ('Team_Name', models.CharField(blank=True, choices=[('Team1', 'Team1'), ('Team2', 'Team2'), ('Team3', 'Team3')], max_length=11, null=True)),
                ('Emp_Id', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
