# Generated by Django 3.2.16 on 2022-11-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='photos/tandas-logo.png', upload_to='photos/'),
        ),
    ]
